name: catena-dev

# This file currently only holds SUPPORTING services for development. It will not run the entirety of Catena.

# TODO: add another compose config that runs the entire stack

services:
  db:
    profiles:
      - db
    image: postgres:18
    environment:
      POSTGRES_USER: catena
      POSTGRES_PASSWORD: catena
      POSTGRES_DB: catena
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql

volumes:
  db_data:
