[build]
builder = "DOCKERFILE"
dockerfilePath = "deployments/proxy.Dockerfile"
watchPatterns = ["deployments/Caddyfile", "deployments/proxy*"]

[deploy]
healthcheckPath = "/"
restartPolicyType = "ON_FAILURE"