// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: git_access_tokens.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createGitAccessToken = `-- name: CreateGitAccessToken :one
insert into git_access_tokens (
  user_id,
  name,
  token_hash,
  token_prefix,
  scopes,
  expires_at
) values (
  $1,
  $2,
  $3,
  $4,
  $5,
  $6
)
returning id, user_id, name, token_hash, token_prefix, scopes, last_used_at, expires_at, revoked_at, created_at, updated_at
`

type CreateGitAccessTokenParams struct {
	UserID      pgtype.UUID
	Name        string
	TokenHash   []byte
	TokenPrefix string
	Scopes      []string
	ExpiresAt   pgtype.Timestamptz
}

func (q *Queries) CreateGitAccessToken(ctx context.Context, arg CreateGitAccessTokenParams) (GitAccessToken, error) {
	row := q.db.QueryRow(ctx, createGitAccessToken,
		arg.UserID,
		arg.Name,
		arg.TokenHash,
		arg.TokenPrefix,
		arg.Scopes,
		arg.ExpiresAt,
	)
	var i GitAccessToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.TokenHash,
		&i.TokenPrefix,
		&i.Scopes,
		&i.LastUsedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getGitAccessTokenByHash = `-- name: GetGitAccessTokenByHash :one
select id, user_id, name, token_hash, token_prefix, scopes, last_used_at, expires_at, revoked_at, created_at, updated_at from git_access_tokens
where token_hash = $1
`

func (q *Queries) GetGitAccessTokenByHash(ctx context.Context, tokenHash []byte) (GitAccessToken, error) {
	row := q.db.QueryRow(ctx, getGitAccessTokenByHash, tokenHash)
	var i GitAccessToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.TokenHash,
		&i.TokenPrefix,
		&i.Scopes,
		&i.LastUsedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listGitAccessTokensByUserID = `-- name: ListGitAccessTokensByUserID :many
select id, user_id, name, token_hash, token_prefix, scopes, last_used_at, expires_at, revoked_at, created_at, updated_at from git_access_tokens
where user_id = $1
  and revoked_at is null
  and (expires_at is null or expires_at > now())
order by created_at desc
`

func (q *Queries) ListGitAccessTokensByUserID(ctx context.Context, userID pgtype.UUID) ([]GitAccessToken, error) {
	rows, err := q.db.Query(ctx, listGitAccessTokensByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GitAccessToken
	for rows.Next() {
		var i GitAccessToken
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.TokenHash,
			&i.TokenPrefix,
			&i.Scopes,
			&i.LastUsedAt,
			&i.ExpiresAt,
			&i.RevokedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeGitAccessToken = `-- name: RevokeGitAccessToken :exec
update git_access_tokens
set revoked_at = now()
where id = $1
  and user_id = $2
  and revoked_at is null
`

type RevokeGitAccessTokenParams struct {
	ID     pgtype.UUID
	UserID pgtype.UUID
}

func (q *Queries) RevokeGitAccessToken(ctx context.Context, arg RevokeGitAccessTokenParams) error {
	_, err := q.db.Exec(ctx, revokeGitAccessToken, arg.ID, arg.UserID)
	return err
}

const touchGitAccessTokenLastUsed = `-- name: TouchGitAccessTokenLastUsed :exec
update git_access_tokens
set last_used_at = now()
where id = $1
`

func (q *Queries) TouchGitAccessTokenLastUsed(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, touchGitAccessTokenLastUsed, id)
	return err
}
