// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: issues.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createIssue = `-- name: CreateIssue :one
insert into issues (
  repository_item_id
) values (
  $1
)
returning repository_item_id, kind, status
`

func (q *Queries) CreateIssue(ctx context.Context, repositoryItemID pgtype.UUID) (Issue, error) {
	row := q.db.QueryRow(ctx, createIssue, repositoryItemID)
	var i Issue
	err := row.Scan(&i.RepositoryItemID, &i.Kind, &i.Status)
	return i, err
}

const getIssueByRepositoryAndNumber = `-- name: GetIssueByRepositoryAndNumber :one
select
  repository_items.id,
  repository_items.repository_id,
  repository_items.number,
  repository_items.kind,
  repository_items.title,
  repository_items.body,
  repository_items.author_id,
  repository_items.created_at,
  repository_items.updated_at,
  repository_items.last_activity_at,
  issues.status
from repository_items
join issues on issues.repository_item_id = repository_items.id
where repository_items.repository_id = $1
  and repository_items.number = $2
`

type GetIssueByRepositoryAndNumberParams struct {
	RepositoryID pgtype.UUID
	Number       int64
}

type GetIssueByRepositoryAndNumberRow struct {
	ID             pgtype.UUID
	RepositoryID   pgtype.UUID
	Number         int64
	Kind           RepositoryItemKind
	Title          string
	Body           *string
	AuthorID       pgtype.UUID
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
	LastActivityAt pgtype.Timestamptz
	Status         IssueStatus
}

func (q *Queries) GetIssueByRepositoryAndNumber(ctx context.Context, arg GetIssueByRepositoryAndNumberParams) (GetIssueByRepositoryAndNumberRow, error) {
	row := q.db.QueryRow(ctx, getIssueByRepositoryAndNumber, arg.RepositoryID, arg.Number)
	var i GetIssueByRepositoryAndNumberRow
	err := row.Scan(
		&i.ID,
		&i.RepositoryID,
		&i.Number,
		&i.Kind,
		&i.Title,
		&i.Body,
		&i.AuthorID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastActivityAt,
		&i.Status,
	)
	return i, err
}

const listIssuesByRepository = `-- name: ListIssuesByRepository :many
select
  repository_items.id,
  repository_items.repository_id,
  repository_items.number,
  repository_items.kind,
  repository_items.title,
  repository_items.body,
  repository_items.author_id,
  repository_items.created_at,
  repository_items.updated_at,
  repository_items.last_activity_at,
  issues.status
from repository_items
join issues on issues.repository_item_id = repository_items.id
where repository_items.repository_id = $1
order by repository_items.last_activity_at desc, repository_items.number desc
`

type ListIssuesByRepositoryRow struct {
	ID             pgtype.UUID
	RepositoryID   pgtype.UUID
	Number         int64
	Kind           RepositoryItemKind
	Title          string
	Body           *string
	AuthorID       pgtype.UUID
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
	LastActivityAt pgtype.Timestamptz
	Status         IssueStatus
}

func (q *Queries) ListIssuesByRepository(ctx context.Context, repositoryID pgtype.UUID) ([]ListIssuesByRepositoryRow, error) {
	rows, err := q.db.Query(ctx, listIssuesByRepository, repositoryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListIssuesByRepositoryRow
	for rows.Next() {
		var i ListIssuesByRepositoryRow
		if err := rows.Scan(
			&i.ID,
			&i.RepositoryID,
			&i.Number,
			&i.Kind,
			&i.Title,
			&i.Body,
			&i.AuthorID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LastActivityAt,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
