// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type IssueStatus string

const (
	IssueStatusOpen       IssueStatus = "open"
	IssueStatusInProgress IssueStatus = "in_progress"
	IssueStatusCompleted  IssueStatus = "completed"
	IssueStatusCancelled  IssueStatus = "cancelled"
)

func (e *IssueStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = IssueStatus(s)
	case string:
		*e = IssueStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for IssueStatus: %T", src)
	}
	return nil
}

type NullIssueStatus struct {
	IssueStatus IssueStatus
	Valid       bool // Valid is true if IssueStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullIssueStatus) Scan(value interface{}) error {
	if value == nil {
		ns.IssueStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.IssueStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullIssueStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.IssueStatus), nil
}

type RepositoryItemKind string

const (
	RepositoryItemKindIssue       RepositoryItemKind = "issue"
	RepositoryItemKindPullRequest RepositoryItemKind = "pull_request"
)

func (e *RepositoryItemKind) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = RepositoryItemKind(s)
	case string:
		*e = RepositoryItemKind(s)
	default:
		return fmt.Errorf("unsupported scan type for RepositoryItemKind: %T", src)
	}
	return nil
}

type NullRepositoryItemKind struct {
	RepositoryItemKind RepositoryItemKind
	Valid              bool // Valid is true if RepositoryItemKind is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullRepositoryItemKind) Scan(value interface{}) error {
	if value == nil {
		ns.RepositoryItemKind, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.RepositoryItemKind.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullRepositoryItemKind) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.RepositoryItemKind), nil
}

type RepositoryVisibility string

const (
	RepositoryVisibilityPrivate RepositoryVisibility = "private"
	RepositoryVisibilityPublic  RepositoryVisibility = "public"
)

func (e *RepositoryVisibility) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = RepositoryVisibility(s)
	case string:
		*e = RepositoryVisibility(s)
	default:
		return fmt.Errorf("unsupported scan type for RepositoryVisibility: %T", src)
	}
	return nil
}

type NullRepositoryVisibility struct {
	RepositoryVisibility RepositoryVisibility
	Valid                bool // Valid is true if RepositoryVisibility is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullRepositoryVisibility) Scan(value interface{}) error {
	if value == nil {
		ns.RepositoryVisibility, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.RepositoryVisibility.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullRepositoryVisibility) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.RepositoryVisibility), nil
}

type GitAccessToken struct {
	ID          pgtype.UUID
	UserID      pgtype.UUID
	Name        string
	TokenHash   []byte
	TokenPrefix string
	Scopes      []string
	LastUsedAt  pgtype.Timestamptz
	ExpiresAt   pgtype.Timestamptz
	RevokedAt   pgtype.Timestamptz
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

type Issue struct {
	RepositoryItemID pgtype.UUID
	Status           IssueStatus
}

type Label struct {
	ID           pgtype.UUID
	RepositoryID pgtype.UUID
	Name         string
	Color        string
	Description  *string
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}

type Repository struct {
	ID             pgtype.UUID
	OwnerID        pgtype.UUID
	Name           string
	Description    *string
	Visibility     RepositoryVisibility
	DefaultBranch  string
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
	ItemPrefix     string
	NextItemNumber int64
}

type RepositoryItem struct {
	ID             pgtype.UUID
	RepositoryID   pgtype.UUID
	Number         int64
	Kind           RepositoryItemKind
	Title          string
	Body           *string
	AuthorID       pgtype.UUID
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
	LastActivityAt pgtype.Timestamptz
}

type RepositoryItemLabel struct {
	RepositoryItemID pgtype.UUID
	LabelID          pgtype.UUID
	CreatedAt        pgtype.Timestamptz
}

type RepositoryItemTimeline struct {
	ID               pgtype.UUID
	RepositoryItemID pgtype.UUID
	ActorID          pgtype.UUID
	Payload          []byte
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
}

type User struct {
	ID          pgtype.UUID
	ClerkUserID string
	Name        string
	DisplayName *string
	AvatarUrl   *string
	Email       string
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}
