// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: repositories.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createRepository = `-- name: CreateRepository :one
insert into repositories (
  owner_id,
  name,
  description,
  visibility,
  default_branch
) values (
  $1,
  $2,
  $3,
  $4,
  $5
)
returning id, owner_id, name, description, visibility, default_branch, created_at, updated_at, item_prefix, next_item_number
`

type CreateRepositoryParams struct {
	OwnerID       pgtype.UUID
	Name          string
	Description   *string
	Visibility    RepositoryVisibility
	DefaultBranch string
}

func (q *Queries) CreateRepository(ctx context.Context, arg CreateRepositoryParams) (Repository, error) {
	row := q.db.QueryRow(ctx, createRepository,
		arg.OwnerID,
		arg.Name,
		arg.Description,
		arg.Visibility,
		arg.DefaultBranch,
	)
	var i Repository
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Name,
		&i.Description,
		&i.Visibility,
		&i.DefaultBranch,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ItemPrefix,
		&i.NextItemNumber,
	)
	return i, err
}

const deleteRepository = `-- name: DeleteRepository :exec
delete from repositories
where id = $1
`

func (q *Queries) DeleteRepository(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteRepository, id)
	return err
}

const getRepositoryByID = `-- name: GetRepositoryByID :one
select id, owner_id, name, description, visibility, default_branch, created_at, updated_at, item_prefix, next_item_number from repositories
where id = $1
`

func (q *Queries) GetRepositoryByID(ctx context.Context, id pgtype.UUID) (Repository, error) {
	row := q.db.QueryRow(ctx, getRepositoryByID, id)
	var i Repository
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Name,
		&i.Description,
		&i.Visibility,
		&i.DefaultBranch,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ItemPrefix,
		&i.NextItemNumber,
	)
	return i, err
}

const getRepositoryByOwnerAndName = `-- name: GetRepositoryByOwnerAndName :one
select repositories.id, repositories.owner_id, repositories.name, repositories.description, repositories.visibility, repositories.default_branch, repositories.created_at, repositories.updated_at, repositories.item_prefix, repositories.next_item_number
from repositories
join users on users.id = repositories.owner_id
where users.name = $1
  and repositories.name = $2
`

type GetRepositoryByOwnerAndNameParams struct {
	OwnerName      string
	RepositoryName string
}

func (q *Queries) GetRepositoryByOwnerAndName(ctx context.Context, arg GetRepositoryByOwnerAndNameParams) (Repository, error) {
	row := q.db.QueryRow(ctx, getRepositoryByOwnerAndName, arg.OwnerName, arg.RepositoryName)
	var i Repository
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Name,
		&i.Description,
		&i.Visibility,
		&i.DefaultBranch,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ItemPrefix,
		&i.NextItemNumber,
	)
	return i, err
}

const listRepositoriesByOwnerFeatured = `-- name: ListRepositoriesByOwnerFeatured :many
select id, owner_id, name, description, visibility, default_branch, created_at, updated_at, item_prefix, next_item_number
from repositories
where owner_id = $1
  and (
    (
      not $2::boolean
      and (
        visibility = 'public'
        or $3::boolean
      )
    )
    or (
      $2::boolean
      and visibility = $4::repository_visibility
      and (
        visibility = 'public'
        or $3::boolean
      )
    )
  )
order by updated_at desc, name asc
limit $5
`

type ListRepositoriesByOwnerFeaturedParams struct {
	OwnerID          pgtype.UUID
	FilterVisibility bool
	IncludePrivate   bool
	Visibility       RepositoryVisibility
	ResultLimit      int32
}

func (q *Queries) ListRepositoriesByOwnerFeatured(ctx context.Context, arg ListRepositoriesByOwnerFeaturedParams) ([]Repository, error) {
	rows, err := q.db.Query(ctx, listRepositoriesByOwnerFeatured,
		arg.OwnerID,
		arg.FilterVisibility,
		arg.IncludePrivate,
		arg.Visibility,
		arg.ResultLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Repository
	for rows.Next() {
		var i Repository
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.Name,
			&i.Description,
			&i.Visibility,
			&i.DefaultBranch,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ItemPrefix,
			&i.NextItemNumber,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRepositoriesByOwnerUpdated = `-- name: ListRepositoriesByOwnerUpdated :many
select id, owner_id, name, description, visibility, default_branch, created_at, updated_at, item_prefix, next_item_number
from repositories
where owner_id = $1
  and (
    (
      not $2::boolean
      and (
        visibility = 'public'
        or $3::boolean
      )
    )
    or (
      $2::boolean
      and visibility = $4::repository_visibility
      and (
        visibility = 'public'
        or $3::boolean
      )
    )
  )
order by updated_at desc, name asc
limit $5
`

type ListRepositoriesByOwnerUpdatedParams struct {
	OwnerID          pgtype.UUID
	FilterVisibility bool
	IncludePrivate   bool
	Visibility       RepositoryVisibility
	ResultLimit      int32
}

func (q *Queries) ListRepositoriesByOwnerUpdated(ctx context.Context, arg ListRepositoriesByOwnerUpdatedParams) ([]Repository, error) {
	rows, err := q.db.Query(ctx, listRepositoriesByOwnerUpdated,
		arg.OwnerID,
		arg.FilterVisibility,
		arg.IncludePrivate,
		arg.Visibility,
		arg.ResultLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Repository
	for rows.Next() {
		var i Repository
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.Name,
			&i.Description,
			&i.Visibility,
			&i.DefaultBranch,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ItemPrefix,
			&i.NextItemNumber,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateRepository = `-- name: UpdateRepository :one
update repositories
set
  name = $2,
  description = $3,
  visibility = $4,
  default_branch = $5
where id = $1
returning id, owner_id, name, description, visibility, default_branch, created_at, updated_at, item_prefix, next_item_number
`

type UpdateRepositoryParams struct {
	ID            pgtype.UUID
	Name          string
	Description   *string
	Visibility    RepositoryVisibility
	DefaultBranch string
}

func (q *Queries) UpdateRepository(ctx context.Context, arg UpdateRepositoryParams) (Repository, error) {
	row := q.db.QueryRow(ctx, updateRepository,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.Visibility,
		arg.DefaultBranch,
	)
	var i Repository
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Name,
		&i.Description,
		&i.Visibility,
		&i.DefaultBranch,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ItemPrefix,
		&i.NextItemNumber,
	)
	return i, err
}
