// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: repository_items.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createRepositoryItem = `-- name: CreateRepositoryItem :one
insert into repository_items (
  repository_id,
  number,
  kind,
  title,
  body,
  author_id
) values (
  $1,
  $2,
  $3,
  $4,
  $5,
  $6
)
returning id, repository_id, number, kind, title, body, author_id, created_at, updated_at, last_activity_at
`

type CreateRepositoryItemParams struct {
	RepositoryID pgtype.UUID
	Number       int64
	Kind         RepositoryItemKind
	Title        string
	Body         *string
	AuthorID     pgtype.UUID
}

func (q *Queries) CreateRepositoryItem(ctx context.Context, arg CreateRepositoryItemParams) (RepositoryItem, error) {
	row := q.db.QueryRow(ctx, createRepositoryItem,
		arg.RepositoryID,
		arg.Number,
		arg.Kind,
		arg.Title,
		arg.Body,
		arg.AuthorID,
	)
	var i RepositoryItem
	err := row.Scan(
		&i.ID,
		&i.RepositoryID,
		&i.Number,
		&i.Kind,
		&i.Title,
		&i.Body,
		&i.AuthorID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastActivityAt,
	)
	return i, err
}

const reserveRepositoryItemNumber = `-- name: ReserveRepositoryItemNumber :one
update repositories
set next_item_number = next_item_number + 1
where id = $1
returning (next_item_number - 1)::bigint as number
`

func (q *Queries) ReserveRepositoryItemNumber(ctx context.Context, id pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, reserveRepositoryItemNumber, id)
	var number int64
	err := row.Scan(&number)
	return number, err
}
