// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :one
insert into users (
  clerk_user_id,
  name,
  display_name,
  avatar_url,
  email
) values (
  $1,
  $2,
  $3,
  $4,
  $5
)
returning id, clerk_user_id, name, display_name, avatar_url, email, created_at, updated_at, description
`

type CreateUserParams struct {
	ClerkUserID string
	Name        string
	DisplayName *string
	AvatarUrl   *string
	Email       string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.ClerkUserID,
		arg.Name,
		arg.DisplayName,
		arg.AvatarUrl,
		arg.Email,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.ClerkUserID,
		&i.Name,
		&i.DisplayName,
		&i.AvatarUrl,
		&i.Email,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Description,
	)
	return i, err
}

const deleteUser = `-- name: DeleteUser :exec
delete from users
where id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteUser, id)
	return err
}

const getUserByClerkUserID = `-- name: GetUserByClerkUserID :one
select id, clerk_user_id, name, display_name, avatar_url, email, created_at, updated_at, description from users
where clerk_user_id = $1
`

func (q *Queries) GetUserByClerkUserID(ctx context.Context, clerkUserID string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByClerkUserID, clerkUserID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.ClerkUserID,
		&i.Name,
		&i.DisplayName,
		&i.AvatarUrl,
		&i.Email,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Description,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
select id, clerk_user_id, name, display_name, avatar_url, email, created_at, updated_at, description from users
where id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id pgtype.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.ClerkUserID,
		&i.Name,
		&i.DisplayName,
		&i.AvatarUrl,
		&i.Email,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Description,
	)
	return i, err
}

const getUserByName = `-- name: GetUserByName :one
select id, clerk_user_id, name, display_name, avatar_url, email, created_at, updated_at, description from users
where name = $1
`

func (q *Queries) GetUserByName(ctx context.Context, name string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByName, name)
	var i User
	err := row.Scan(
		&i.ID,
		&i.ClerkUserID,
		&i.Name,
		&i.DisplayName,
		&i.AvatarUrl,
		&i.Email,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Description,
	)
	return i, err
}

const updateUserProfile = `-- name: UpdateUserProfile :one
update users
set
  name = $2,
  display_name = $3,
  avatar_url = $4,
  description = $5
where id = $1
returning id, clerk_user_id, name, display_name, avatar_url, email, created_at, updated_at, description
`

type UpdateUserProfileParams struct {
	ID          pgtype.UUID
	Name        string
	DisplayName *string
	AvatarUrl   *string
	Description *string
}

func (q *Queries) UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserProfile,
		arg.ID,
		arg.Name,
		arg.DisplayName,
		arg.AvatarUrl,
		arg.Description,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.ClerkUserID,
		&i.Name,
		&i.DisplayName,
		&i.AvatarUrl,
		&i.Email,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Description,
	)
	return i, err
}
