import { ClerkProvider } from "@clerk/nextjs";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { PropsWithChildren } from "react";

import { cn } from "@/lib/utils";
import AuthProvider from "@/providers/AuthProvider";
import QueryClientProvider from "@/providers/QueryClientProvider";

import "./globals.css";

const sansFont = Geist({ subsets: ["latin"], variable: "--font-sans" });

const monoFont = Geist_Mono({
    variable: "--font-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }: PropsWithChildren) {
    return (
        <html
            lang="en"
            className={cn(
                "h-full",
                "antialiased",
                sansFont.variable,
                monoFont.variable,
                "font-sans",
            )}
        >
            <body className="flex min-h-full flex-col">
                <ClerkProvider>
                    <QueryClientProvider>
                        <AuthProvider>{children}</AuthProvider>
                    </QueryClientProvider>
                </ClerkProvider>
            </body>
        </html>
    );
}
