/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health Check
         * @description Check the health of the API service. Note that this will only ever return "ok".
         */
        get: operations["healthz"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/user": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Authenticated User
         * @description Retrieve the authenticated Catena user, creating the local user record from Clerk if needed.
         */
        get: operations["getAuthenticatedUser"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/users/clerk/{clerkUserId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get User By Clerk ID
         * @description Retrieve the authenticated Catena user by Clerk user ID. The path Clerk user ID must match the authenticated Clerk principal.
         */
        get: operations["getUserByClerkUserId"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/users/name/{name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get User By Name
         * @description Retrieve a public Catena user by username.
         */
        get: operations["getUserByName"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/clerk/sign-in-token": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create Clerk Sign-In Token
         * @description Create a Clerk sign-in token for the authenticated user. This is intended for CLI login handoff flows.
         */
        post: operations["createClerkSignInToken"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/git-access-tokens": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Git Access Tokens
         * @description List Git access tokens for the authenticated user.
         */
        get: operations["listGitAccessTokens"];
        put?: never;
        /**
         * Create Git Access Token
         * @description Create a Git access token for HTTP Git authentication. The raw token is returned once.
         */
        post: operations["createGitAccessToken"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/git-access-tokens/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Revoke Git Access Token
         * @description Revoke a Git access token owned by the authenticated user.
         */
        delete: operations["revokeGitAccessToken"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/repositories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create Repository
         * @description Create a repository owned by the authenticated user.
         */
        post: operations["createRepository"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/repositories/{owner}/{repository}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Repository
         * @description Retrieve a repository by owner and name. Public repositories can be retrieved without authentication.
         */
        get: operations["getRepositoryByOwnerAndName"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/repositories/{owner}/{repository}/readme": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Repository README
         * @description Retrieve the first supported README file in a repository directory. Public repositories can be retrieved without authentication.
         */
        get: operations["getRepositoryReadme"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/repositories/{owner}/{repository}/latest-commit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Repository Latest Commit
         * @description Retrieve the most recent commit for a repository ref and optional path. Public repositories can be retrieved without authentication.
         */
        get: operations["getRepositoryLatestCommit"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/repositories/{owner}/{repository}/git-path/resolve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Resolve Repository Git Path
         * @description Resolve a GitHub-style path into a repository ref and optional path. Public repositories can be resolved without authentication.
         */
        get: operations["resolveRepositoryGitPath"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/repositories/{owner}/{repository}/refs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Repository Refs
         * @description List repository refs. Only branch refs are supported for now.
         */
        get: operations["listRepositoryRefs"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/repositories/{owner}/{repository}/tree": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Repository Tree
         * @description Retrieve the files and directories at a repository path. Public repositories can be retrieved without authentication.
         */
        get: operations["getRepositoryTree"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        CreateClerkSignInTokenResponse: {
            token: string;
        };
        CreateGitAccessTokenRequest: {
            /** @example Local development laptop */
            name: string;
            /**
             * @example [
             *       "repo:read",
             *       "repo:write"
             *     ]
             */
            scopes?: string[];
            /** Format: date-time */
            expiresAt?: string | null;
        };
        CreateGitAccessTokenResponse: {
            /** @example ctn_pat_example */
            token: string;
            accessToken: components["schemas"]["GitAccessToken"];
        };
        CreateRepositoryRequest: {
            /** @example catena */
            name: string;
            /** @example A Git hosting platform. */
            description?: string | null;
            visibility?: components["schemas"]["RepositoryVisibility"];
            /**
             * @description Defaults to `main` when omitted.
             * @default main
             */
            defaultBranch?: string;
        };
        CreateRepositoryResponse: components["schemas"]["Repository"] & {
            ownerName: string;
        };
        Error: {
            error: string;
        };
        GitAccessToken: {
            /** Format: uuid */
            id: string;
            name: string;
            tokenPrefix: string;
            scopes: string[];
            /** Format: date-time */
            lastUsedAt?: string | null;
            /** Format: date-time */
            expiresAt?: string | null;
            /** Format: date-time */
            revokedAt?: string | null;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        Repository: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            ownerId: string;
            ownerName: string;
            name: string;
            description?: string | null;
            visibility: components["schemas"]["RepositoryVisibility"];
            defaultBranch: string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        /**
         * @default private
         * @enum {string}
         */
        RepositoryVisibility: "private" | "public";
        ListRepositoryRefsResponse: {
            refs: components["schemas"]["RepositoryRef"][];
        };
        RepositoryRef: {
            name: string;
            type: components["schemas"]["RepositoryRefType"];
            commitOid: string;
            isDefault: boolean;
        };
        /** @enum {string} */
        RepositoryRefType: "branch";
        RepositoryReadme: {
            ref: string;
            commitOid: string;
            path: string;
            name: string;
            oid: string;
            /** Format: int64 */
            size: number;
            /** @example utf-8 */
            encoding: string;
            content: string;
        };
        RepositoryLatestCommit: {
            ref: string;
            commitOid: string;
            shortOid: string;
            messageHeadline: string;
            message: string;
            authorName: string;
            authorEmail: string;
            /** Format: date-time */
            authoredAt: string;
            committerName: string;
            committerEmail: string;
            /** Format: date-time */
            committedAt: string;
        };
        ResolvedRepositoryGitPath: {
            ref: string;
            commitOid: string;
            path: string;
            /** @enum {string} */
            pathType: "root" | "blob" | "tree" | "commit";
        };
        RepositoryTree: {
            ref: string;
            commitOid: string;
            path: string;
            entries: components["schemas"]["RepositoryTreeEntry"][];
        };
        RepositoryTreeEntry: {
            name: string;
            path: string;
            /** @enum {string} */
            type: "blob" | "tree" | "commit";
            oid: string;
            /** Format: int64 */
            size?: number | null;
        };
        User: {
            /** Format: uuid */
            id: string;
            name: string;
            displayName?: string | null;
            avatarUrl?: string | null;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
    };
    responses: {
        /** @description Bad Request */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Conflict */
        Conflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Forbidden */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Internal Server Error */
        InternalServerError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Not Found */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Unauthorized */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type SchemaCreateClerkSignInTokenResponse =
    components["schemas"]["CreateClerkSignInTokenResponse"];
export type SchemaCreateGitAccessTokenRequest =
    components["schemas"]["CreateGitAccessTokenRequest"];
export type SchemaCreateGitAccessTokenResponse =
    components["schemas"]["CreateGitAccessTokenResponse"];
export type SchemaCreateRepositoryRequest =
    components["schemas"]["CreateRepositoryRequest"];
export type SchemaCreateRepositoryResponse =
    components["schemas"]["CreateRepositoryResponse"];
export type SchemaError = components["schemas"]["Error"];
export type SchemaGitAccessToken = components["schemas"]["GitAccessToken"];
export type SchemaRepository = components["schemas"]["Repository"];
export type SchemaRepositoryVisibility =
    components["schemas"]["RepositoryVisibility"];
export type SchemaListRepositoryRefsResponse =
    components["schemas"]["ListRepositoryRefsResponse"];
export type SchemaRepositoryRef = components["schemas"]["RepositoryRef"];
export type SchemaRepositoryRefType =
    components["schemas"]["RepositoryRefType"];
export type SchemaRepositoryReadme = components["schemas"]["RepositoryReadme"];
export type SchemaRepositoryLatestCommit =
    components["schemas"]["RepositoryLatestCommit"];
export type SchemaResolvedRepositoryGitPath =
    components["schemas"]["ResolvedRepositoryGitPath"];
export type SchemaRepositoryTree = components["schemas"]["RepositoryTree"];
export type SchemaRepositoryTreeEntry =
    components["schemas"]["RepositoryTreeEntry"];
export type SchemaUser = components["schemas"]["User"];
export type ResponseBadRequest = components["responses"]["BadRequest"];
export type ResponseConflict = components["responses"]["Conflict"];
export type ResponseForbidden = components["responses"]["Forbidden"];
export type ResponseInternalServerError =
    components["responses"]["InternalServerError"];
export type ResponseNotFound = components["responses"]["NotFound"];
export type ResponseUnauthorized = components["responses"]["Unauthorized"];
export type $defs = Record<string, never>;
export interface operations {
    healthz: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example ok */
                        status?: string;
                    };
                };
            };
        };
    };
    getAuthenticatedUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            401: components["responses"]["Unauthorized"];
            500: components["responses"]["InternalServerError"];
        };
    };
    getUserByClerkUserId: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                clerkUserId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalServerError"];
        };
    };
    getUserByName: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalServerError"];
        };
    };
    createClerkSignInToken: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreateClerkSignInTokenResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            500: components["responses"]["InternalServerError"];
        };
    };
    listGitAccessTokens: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GitAccessToken"][];
                };
            };
            401: components["responses"]["Unauthorized"];
            500: components["responses"]["InternalServerError"];
        };
    };
    createGitAccessToken: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateGitAccessTokenRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreateGitAccessTokenResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            500: components["responses"]["InternalServerError"];
        };
    };
    revokeGitAccessToken: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            500: components["responses"]["InternalServerError"];
        };
    };
    createRepository: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateRepositoryRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreateRepositoryResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            409: components["responses"]["Conflict"];
            500: components["responses"]["InternalServerError"];
        };
    };
    getRepositoryByOwnerAndName: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                owner: string;
                repository: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Repository"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalServerError"];
        };
    };
    getRepositoryReadme: {
        parameters: {
            query?: {
                /** @description Branch, tag, or commit to read from. Defaults to the repository default branch. */
                ref?: string;
                /** @description Directory path to search for a README in. Defaults to the repository root. */
                path?: string;
            };
            header?: never;
            path: {
                owner: string;
                repository: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RepositoryReadme"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalServerError"];
        };
    };
    getRepositoryLatestCommit: {
        parameters: {
            query?: {
                /** @description Branch, tag, or commit to read from. Defaults to the repository default branch. */
                ref?: string;
                /** @description Repository path to constrain the latest commit lookup. Defaults to the repository root. */
                path?: string;
            };
            header?: never;
            path: {
                owner: string;
                repository: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RepositoryLatestCommit"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalServerError"];
        };
    };
    resolveRepositoryGitPath: {
        parameters: {
            query: {
                /** @description Ambiguous path containing a ref followed by an optional repository path. */
                path: string;
            };
            header?: never;
            path: {
                owner: string;
                repository: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResolvedRepositoryGitPath"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalServerError"];
        };
    };
    listRepositoryRefs: {
        parameters: {
            query?: {
                /** @description Ref type to list. Currently only `branch` is supported. */
                type?: components["schemas"]["RepositoryRefType"];
            };
            header?: never;
            path: {
                owner: string;
                repository: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListRepositoryRefsResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalServerError"];
        };
    };
    getRepositoryTree: {
        parameters: {
            query?: {
                /** @description Branch, tag, or commit to read from. Defaults to the repository default branch. */
                ref?: string;
                /** @description Directory path to list. Defaults to the repository root. */
                path?: string;
            };
            header?: never;
            path: {
                owner: string;
                repository: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RepositoryTree"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalServerError"];
        };
    };
}
